### ISSUE TITLE
notes on the website 2.0

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil-labs-website#104]
For some reason people I have seen using the page (including me) have some delay until clicking at the navbar (pupil, VR/AR). Creating alternatives for reaching at the navbar pages may improve site navigation. For example, the welcome page could have each project short presented at the body.

**Comment by willpatera** [comment]
Hi @cpicanco - Thanks for the feedback, but I am not sure I understand. Are you reporting a technical issue or UI/UX feedback?

**Comment by cpicanco** [comment]
Not a technical issue. Just an observation for your consideration.

**Comment by cpicanco** [comment]
It is kind of embarrassing for me not be able to attend to the hyperlinks. Maybe the problem was in my monitor, maybe the problem was in my eyes! Apologies!

**Comment by willpatera** [comment]
Hi @cpicanco - No need to apologize. If links in the nav bar are difficult for you to see, then (as you mention) it might also be difficult for others. If you can provide concrete feedback on a specific instance or instances where it is difficult for you by making a screenshot with notes, that would be useful.

White nav link text, when overlaid on image pixels that are also white, makes the nav links very difficult if not impossible to see. This is an issue that might be solved by a very subtle drop shadow for text when the header background is transparent. 

If you'd like to re-open with feedback, you are welcome to do so 😸
