### ISSUE TITLE
Blog post on gitter interview

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#116]
create blog post and link to the interview conducted with gitter.

**Comment by nathakits** [comment]
https://github.com/nathakits/pupil-labs-website/commit/e3ecfaea00d977bf717ea207c5d3dccdb45e4a7e

**Comment by willpatera** [comment]
@nathakits - see my comments on the code

**Comment by nathakits** [comment]
https://github.com/nathakits/pupil-labs-website/commit/43ce0b92373c3ec8006b033efd5987ef9fa1ab31
