### ISSUE TITLE
Performance - reduce favicon `.png` size (slowing page load)

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#134]
Reduce favicon size/resolution - adds time to load.

**Comment by nathakits** [comment]
updated compressed favicons from `web-media/compress_favicons` submodule

https://github.com/pupil-labs/pupil-labs-website/pull/137

**Comment by nathakits** [comment]
Move PR to web-media - https://github.com/pupil-labs/web-media/pull/3
