### ISSUE TITLE
Performance - reduce `.png` file sizes

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#135]
Go through `.png`'s used on the site and reduce file size but retain quality.

**Comment by nathakits** [comment]
https://github.com/pupil-labs/pupil-labs-website/pull/138

**Comment by nathakits** [comment]
Move PR to web-media - https://github.com/pupil-labs/web-media/pull/5

**Comment by willpatera** [comment]
files are still very large...

**Comment by willpatera** [comment]
favicons are still problematic... requires more fixing.
