### ISSUE TITLE
Form - all form elements must have a label attribute

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#144]
All Form elements must have label attributes for accessibility. Use `lighthouse` tool to check which elements are breaking that requirement on `/` (see `home.jade`) and `/cart` (see `order-form.jade` and `pupil_store.coffee`)  

Labels can also be hidden (offscreen) if it conflicts with existing structure, as this is an accessibility issue (see this [page](http://webaim.org/techniques/forms/advanced#hiddenlabel))

**Comment by nathakits** [comment]
Branch `form_label_attribute`
Commit - https://github.com/nathakits/pupil-labs-website/commit/0fb03811a9107fb51202fd214a43cd29b9603691

Added hidden label attribute for `home.jade` so far. Lighthouse report is A-OKAY.

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-labs-website/pulls

- [x] Home 
- [X] Cart 
- [X] Order-form

Pupil Store will be on a new branch

**Comment by willpatera** [comment]
Closing - complete
