### ISSUE TITLE
Webfonts and Font loading optimization

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#146]
Improve loading for web-fonts based on suggestions outlined in [this article](http://meowni.ca/posts/web-fonts/).

**Comment by nathakits** [comment]
Branch `webfont_load_optimize`- https://github.com/nathakits/pupil-labs-website/tree/webfont_load_optimize
JS - https://github.com/nathakits/pupil-labs-website/blob/webfont_load_optimize/assets/js/lazyload/lazyload.js

I tried using both `blocking` and `XHR(async)` methods to lazy load the web-fonts, but sometimes for both methods the JS script doesn't load the web-fonts. When it does load, the `start-time` of the web-font is slower than from the CSS but it does make the file size smaller and load time faster.

Also tried loading the local fonts `Regular` and `AtlasGroteskRegular` but couldn't.

#### Performance
Tested the `Space-Mono` font on a `good 3G network`
CSS - 956b / ~ 103ms (faster start time)
Block / XHR - 490b / ~62ms (slower start time)

**Comment by willpatera** [comment]
This appears to work: 

```javascript
document.body.onload = function() {
  function xmlRequest(url){
    var xhr = new XMLHttpRequest();

    xhr.open('GET', url, true);
    xhr.onreadystatechange = function () {
      if (xhr.readyState == 4 && xhr.status == 200) {
        var style = document.createElement('style');
        style.innerHTML = xhr.responseText;
        document.head.appendChild(style);
      }
    };
    xhr.send();

  }

  var urls = ["media/fonts/Regular-Semibold.woff",
          "media/fonts/AtlasGrotesk-Regular-Web.woff",
          'https://fonts.googleapis.com/css?family=Space+Mono']

  for (var i = 0; i < urls.length; i++) {
    xmlRequest(urls[i]);
  }
}
```

@nathakits - please evaluate performance and post differences between current master and your branch with these changes.

**Comment by nathakits** [comment]
Lazyload Test

|                      | Good 2G |          | Ethernet |             |
| ----------------- |:-----------:|:-------:|:-----------:|:----------:|
| Space Mono | 490B      | 185ms | 956B    | 341ms |
| AtlasGrotesk |  53.7KB | 2.58s |  53.7KB  | 4.19s   |
| Regular |          53.2KB | 2.60s |  53.2KB  | 4.24     |
| | | | | |
| Total load | 5.04s | | 5.46s |  |

**Comment by nathakits** [comment]
Testing `font-face observer` - https://github.com/nathakits/pupil-labs-website/tree/font_face_observer
In reference to this - http://helenvholmes.com/writing/type-is-your-right

**Comment by nathakits** [comment]
font fallback - https://github.com/nathakits/pupil-labs-website/tree/font_face_observer
Testing font fallback with header. 
  - h1 font = 2.55em
  - Added `fonts-loaded` class to h1 with 2.8em with script

**Comment by nathakits** [comment]
Still working on this. Found this article showing many approaches to font loading.

A COMPREHENSIVE GUIDE TO FONT LOADING STRATEGIES - https://www.zachleat.com/web/comprehensive-webfonts/
