### ISSUE TITLE
Store images - make jpeg versions of files

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#156]
- [ ] For images on the store make .jpeg versions of files in web-media and reduce width to 450px maximum. Keep file names the same and in the same directory, but add a new `.jpg` file 
- [ ] Update file name suffixes in `product_list.coffee` 

Support remains as .svg files

**Comment by nathakits** [comment]
- [X] Compress JPGs to 450px
- [X] Update name suffixes

PR - webmedia - https://github.com/pupil-labs/web-media/pull/7

**Comment by willpatera** [comment]
merged to dev with #161
