### ISSUE TITLE
Manifest fix

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#158]
Manifest is only correctly linked for the home page `/` and not other pages on the website. Check the url in the header file. 

This can be fixed (I am pretty sure in the path declaration):

from this
`href="manifest/manifest.json"`
to this
`href="/manifest/manifest.json"`

**Comment by nathakits** [comment]
PR -https://github.com/pupil-labs/pupil-labs-website/pull/159

**Comment by willpatera** [comment]
Merged. Closing.
