### ISSUE TITLE
IE11 - test forms

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#172]
@nathakits - please test order form with IE11 and inspect .js processes.

**Comment by nathakits** [comment]
![ie11_test-forms](https://cloud.githubusercontent.com/assets/17331040/20780992/1f43c0a8-b7b2-11e6-9233-40c87dbcb18e.PNG)

**Comment by willpatera** [comment]
The error in the console is not related to the form. As far as I can see there is no issue with the form in IE11 from this test.
