### ISSUE TITLE
Blog - overflow for project release tags

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#189]
Overflow for short (small Y height) windows for the blog post tags. 

![pupil-labs com-blog-](https://cloud.githubusercontent.com/assets/1407224/21338505/58e6dc22-c6a9-11e6-915e-3a7fdcee0444.png)

**Comment by nathakits** [comment]
Added a height breakpoint for the tag overflow - https://github.com/pupil-labs/pupil-labs-website/pull/190
