### ISSUE TITLE
Menu missing in Samsung's default Android browser

### ISSUE THREAD

**Issue by marc-tonsen** [pupil-labs/pupil-labs-website#202]
There is no menu button in the default browser on my Samsung Galaxy A5 (see attached screenshot). The browser is called "Internet" in version 4.0.20-62, Android version is 6.0.1.
![screenshot_2017-01-30-14-31-28](https://cloud.githubusercontent.com/assets/22236733/22425047/9b982cb8-e6f9-11e6-8925-0df76f2f3f85.png)

**Comment by cpicanco** [comment]
Cannot reproduce with this one: Pixi4, Alcatel.



![screenshot_20170130-113750](https://cloud.githubusercontent.com/assets/6511849/22427250/15bfb982-e70b-11e6-9569-b3d9a7783675.png)

![screenshot_20170130-113805](https://cloud.githubusercontent.com/assets/6511849/22427176/c750d574-e70a-11e6-9dcb-e77b4102f395.png)

**Comment by willpatera** [comment]
@marc-tonsen - thanks for the report. I will look into this issue tomorrow. 

The 'Internet' browser is on the A5 used Chromium and is likely at least Chromium 38. 

This is likely a CSS or js incompatibility.

**Comment by willpatera** [comment]
@marc-tonsen - I think I found the issue. `css` related I believe or caused by overly aggressive css cleaning. I will push changes to master. Please refresh the page and let me know if fixed.

If no menu bar appears, please try clicking on the area where the menu button should be and let me know if the menu appears.

**Comment by marc-tonsen** [comment]
I just checked again, it is actually working now. I am using "Internet" in version 5.4.00-75 by now, so not sure if it was an update to the website or the browser that fixed it!

**Comment by willpatera** [comment]
No changes were made to resolve this on our end. I assume this was resolved by Samsung updating their "Internet" browser.
