### ISSUE TITLE
Add images for pupil-docs blog post

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#205]
@nathakits - please take a screenshot of pupil-docs-website and add to the draft of my [blog post draft](https://github.com/pupil-labs/pupil-labs-website/blob/dev/contents/articles/2017-03_new-docs-website/index.md). 

Please also do spell check and fix any typos if you find any and make a pr to `dev` branch.

**Comment by nathakits** [comment]
@willpatera PR - https://github.com/pupil-labs/pupil-labs-website/pull/206
Spellchecked ( no typo found ) and added the screenshot to the draft
