### ISSUE TITLE
Performance - Update images to .webp

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-labs-website#211]
Update images to .webp with jpg fallback in <picture> tag,

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-labs-website/pull/212

@willpatera - please review this webp PR

**Comment by nathakits** [comment]
@willpatera - The webp task in the `.travisyml` file is currently in the wrong order. Currently it's after the build task so the webp mixin wasn't able to find the `.webp` images.

Also two of the image in the image folder have the same name causing the wrong image to show on the site. 

I will update the travis file and will rename the image in the next PR

**Comment by nathakits** [comment]
PR - https://github.com/pupil-labs/pupil-labs-website/pull/213

**Comment by willpatera** [comment]
todo - test and merge into master.
