### ISSUE TITLE
Fixes to html, links, and images

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#214]
@nathakits please see: https://travis-ci.org/pupil-labs/pupil-docs-website/jobs/239915942#L916-L1026

Please make separate issues for each category of issue listed. 
- missing alt tags
- broken links
- missing srcset attributes (this one is a bit tricky because it may be set dynamically with .js lazyloading) 

Note that line numbers refer to the built index.html file. So, it would be wise to build the site locally to debug these issues. 

Pay attention only to the master branch here and not to other tags. Hence why I highlighted L916-L1026 in the travis link.

**Comment by nathakits** [comment]
Lazysizes srcset
https://github.com/aFarkas/lazysizes#modern-transparent-srcset-pattern
https://github.com/aFarkas/lazysizes/issues/150

**Comment by willpatera** [comment]
@nathakits - we should have a `src` attribute with a lqip image - https://github.com/aFarkas/lazysizes#lqipblurry-image-placeholderblur-up-image-technique

**Comment by willpatera** [comment]
Migrated.
