### ISSUE TITLE
Update products section in footer

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#250]
Update products section in footer:

`Mobile Eye Tracking Headset`
`HTC Vive Eye Tracking Add-on`
`HoloLens Eye Tracking Add-on`
`Oculus Eye Tracking Add-on`
`Support Contract`
`200hz Eye Camera`
`Pupil Mobile Bundle`

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-labs-website/pulls

**Comment by willpatera** [comment]
Merged, closing :smile:
