### ISSUE TITLE
Add Discord link in the home page

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-labs-website#265]
add Discord link to the `pupil` chat under `Pupil is Open Source` section.

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-labs-website/pull/266

I thought of just linking it in the text but thought it would be alot more distinguishable from other elements if it was a button. And it would be more inviting for users to press it as well.

**Comment by willpatera** [comment]
Thanks! Merged; closing 😸
