### ISSUE TITLE
remove references to Google Groups

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#269]
remove references in the website to Google Groups. Leave reference in all blog posts as this is historical data - but remove from main routes.

**Comment by nathakits** [comment]
@willpatera - Correct me if i'm wrong, but I don't think there is any reference to Google Groups on the website.

**Comment by willpatera** [comment]
https://github.com/pupil-labs/pupil-labs-website/blob/master/contents/newsletter_success/index.md

and

https://github.com/pupil-labs/pupil-labs-website/blob/master/contents/pupil/features/communitylicense/community.md

**Comment by nathakits** [comment]
@willpatera - PR https://github.com/pupil-labs/pupil-labs-website/pull/272

**Comment by willpatera** [comment]
Thanks! Merged; closing 😸
