### ISSUE TITLE
RSS - Missing https protocol in permalink

### ISSUE THREAD

**Issue by imagoiq** [pupil-labs/pupil-labs-website#282]
Hi,

Permalink for every articles are need the https protocol. Links are wrongly interprets by rss reader, like that : "https://pupil-labs.com/pupil-labs.com/blog/2018-03/pupil-capture-player-and-service-release-v1-5/"

Not sure what is the best way to fix. Either by
* Adding it to the config locals.url
* Adding it to the feed.jade template

**Comment by willpatera** [comment]
@imagoiq this shoudl be fixed now with https://github.com/pupil-labs/pupil-labs-website/commit/581bdd6450448d7e814d938ba5c40c6cbf45b70c - please let me know if it isn't and I will re-open this issue. Thanks for pointing this out :smile:
