### ISSUE TITLE
Update font

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#30]
Consider using [`Post Grotesk`](http://vllg.com/incubator/post-grotesk) or [`Regular`](https://vllg.com/a2-type/regular/)

**Comment by nathakits** [comment]
Latest Commit : 
Header Font : Montserrat
Copy Text : Helvetica

**Comment by willpatera** [comment]
We are going with `Regular Semi Bold` and `Atlas Grotesk Regular` for copy text
