### ISSUE TITLE
Country Dropdown

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#308]
## Problem
Autofill list blocks country dropdown list. 

## Solutions
1. Block autofill of country input
1. Adjust the positioning of autofill options so that country names are not blocked.

**Comment by nathakits** [comment]
I think the way to go is solution 1

**Comment by willpatera** [comment]
Still a problem in Chrome v < 68 - Chrome is overriding `autocomplete="off"`

**Comment by willpatera** [comment]
This has been somewhat resolved with recent changes to `/cart` - will re-open if we discover more issues with autocomplete.
