### ISSUE TITLE
Update blog layout

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-labs-website#317]
minor update to the blog design, updating all the featured images to all have the same rectangular size/shape with colored bg and update to the typography.

**Comment by willpatera** [comment]
@nathakits go ahead and start working on this - and make any minor changes to existing typography as needed.

**Comment by nathakits** [comment]
Notes from discussions:
Incremental update to the blog page
1. Pinned latest release at the top of the page
2. Follow the same layout (news + releases) with a style update
Next incremental update
3. Filtering to show only news or releases
