### ISSUE TITLE
Data output - (response needed to start our experiment)

### ISSUE THREAD

**Issue by ganauniv** [pupil-labs/pupil-labs-website#342]
Hi, we are working with a pupil labs headset (2 eye-cameras, no world camera), we don't run calibration as it is not possible or needed as we are only interested in the diameter as a consequence to auditory stimuli.  
After following your instructions of pupil detection, we realized there is always this change in sphere center location like a series of data with a certain sphere center values and then they changes and there is a series of other values. I don't know how to explain it better, so I attach another screenshot of another pupil_position file (attach n.2).
So, my question is: it is normal that these values are going to change during a recording or they must not change during all the entire recording?

We wanted to understand if there is a way to cope with crazy higher pupil diameter values that tend to appear sometimes. We noticed that these kind of values appear not only when the confidence (both 3D model and normal) are not good (below 0.6) but also when everything is good. We also noticed that when the sphere center values (x,y,z) change, the pupil diameter changes, but this happens also when we have "normal" pupil diameter values. So, we were wondering:
 is it normal that the sphere center values change or they should be the same for all the recording? And also, do we need to set differently our parameters in order to cope with this higher diameter values?

We are in a HURRY to have this under control to begin our project so we would be more than happy and appreciate your help. I attach the files that could be helpful to understand our question.

Thanks for your attention.
![attach n 2](https://user-images.githubusercontent.com/51618954/59187197-2fbf2000-8b75-11e9-8fc5-ff370aaf0e4d.png)

**Comment by willpatera** [comment]
@ganauniv this repo is for  the old Pupil Labs website (pupil-labs.com) if you want to ask a question or report an issue regarding Pupil - please do so at https://github.com/pupil-labs/pupil (if you haven't done so already), you can also get in touch by chat via https://pupil-labs.com/chat (this will redirect you to Discord chat server).
