### ISSUE TITLE
add `featured_img` in articles metadata

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#49]
For each article add `featured_img` path using the best (most communicative) image for each post. 

If only video exists for that post, then make or use a poster frame. The poster frame will need to be uploaded to the `web-media` repo. 

If no image exists, then use a relevant placeholder image. See #48 in reference to placeholder images for software releases.

**Comment by nathakits** [comment]
Blog articles metadata #52

**Comment by willpatera** [comment]
Merged and closing issue. Thanks!
