### ISSUE TITLE
bkg video opt-in play on mobile

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#60]
On mobile the vr-ar background video should be played if user opts-in to play the video, otherwise `#video-cover` is shown with a play button overlay using https://design.google.com/icons/#ic_play_arrow for the play button inside of a translucent circle.

**Comment by nathakits** [comment]
Added google material play button with translucent circle
Still couldn't get the play element to align properly

https://github.com/nathakits/pupil-labs-website/commit/3bf6ff16cb0aeaec366937e4e20493a30961e444
