### ISSUE TITLE
Styling small improvements

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-labs-website#62]
- [x] Blog - Pupil Service Blog entry preview image is to big.
 - [x] Footer - Products overview, entries should not break line. Make them shorter.
 - [x] Start Page - Try to mirror the Pupil Platform image for better optical balance
 - [x] Start Page - Github activity. Show PRs and Issues
 - [x] Store - Add max width to align with other pages.
 - [x] Cart - Add max width to align with other pages.
 - [x] Docs - Link not working

**Comment by willpatera** [comment]
docs link will work on production site. checking this off the list.

**Comment by willpatera** [comment]
migrated blog image issue to it's own issue and checked off here.
