### ISSUE TITLE
test on android and iOS

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#78]
@nathakits - test on android

I will test iOS

**Comment by willpatera** [comment]
large background images get "re-rendered" on fast scroll-up in mobile. This is a wontfix with current implementation. We need to reconsider how we implement large background images (perhaps using canvas is a more sustainable solution), and actually loading `img` and showing on canvas when ready so they are properly cached.

**Comment by nathakits** [comment]
@willpatera - The styling of the bullet points on careers page still needs work

**Comment by nathakits** [comment]
Also would be nice if we could swipe right to show the sidenav bar without having to click on it every time. Just a thought

**Comment by willpatera** [comment]
@nathakits -- work on the styling of the bullet points for the `ul` on `/careers`

Swipe from left to show nav drawer is nice, but fails hard on iOS and other mobile devices where screen edge swipes are used to move to the next system window or for shortcuts. Hence why it is not implemented.

**Comment by willpatera** [comment]
need tests for iOS - will open new issue for just this.
