### ISSUE TITLE
Edge Browser, IE 11 - Background video black background

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#82]
Remove black background for `video` element in Edge and IE 11.

**Comment by nathakits** [comment]
@willpatera - BKG video cannot be played

**Comment by willpatera** [comment]
On edge or IE 11 - be specific

**Comment by willpatera** [comment]
BKG video can play on Edge and IE11 now - working on background bars for scaled video now.

**Comment by willpatera** [comment]
Black bars are related to video scaling and [lack of support](http://caniuse.com/#search=object-fit) for css property `object-fit` in Edge Browser and IE11.

**Comment by willpatera** [comment]
fixed black background on Edge and IE11
