### ISSUE TITLE
transition to `canvas` for blur-up technique

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-labs-website#89]
transition to canvas for blur-up technique, and store images within img tags instead of as bkg images so that they are properly cached by the browser. This author has a [great writeup](http://www.anthonykoch.com/blog/medium-style-images/) of this technique employed by Medium.

**Comment by willpatera** [comment]
@nathakits - post performance tests and links to your branch in this issue.

**Comment by nathakits** [comment]
#### Performance test

Performance test from an average of 10 tests.

|Type| Size (kb)   | Finish (ms) | DOM (ms) | Load (ms) |
|:-----:| -------------- |:--------------:| --------------:|:-------------:|
| Canvas |782  | 79.3 | 44.6 | 65.8 |
| Bkg Img |897  | 113.4 | 102.1 | 118 |

#### Link to branch
canvas test - https://github.com/nathakits/pupil-labs-website/tree/canvas_test
bkg backface test - https://github.com/nathakits/pupil-labs-website/tree/bkg_backface_render

**Comment by nathakits** [comment]
#### Canvas
The canvas implementation seems to be faster but needs more work in terms of coding to achieve the same level as Backround image with CSS. ie `Background : cover`. Canvas uses both JS and CSS to style the image.

Canvas makes use of JS to push pixels of the image to the canvas. For the new image to appear, new pixels needs to be pushed to replace the previous pixels.
#### Background
Background image only uses CSS to style the image. `Background : cover` makes it very easy to scale the image on the webpage. But comes with a minor performance issue on mobile devices, where fast scrolling affects the rendering of the image. 

The image loads again in choppy blocks. But a simple css styling `backface visibility : hidden` solves this issue but seems to lag on low performance mobile devices.

**Comment by willpatera** [comment]
I will close this issue, but we should keep the branch for further testing.
