### ISSUE TITLE
Desktop browser - fix missing cart badge

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-labs-website#90]
Cart badge disappears when no items are added to the cart

**Comment by nathakits** [comment]
Seems like all the browsers have this problem except Chromium on Ubuntu.

**Comment by nathakits** [comment]
Just checked again from the latest pull from `dev` branch. It seems the problem might be somwhere else. The css is has not been `uncss` but the problem still exists.

**Comment by willpatera** [comment]
if cart is empty there is no counter. This is working as designed.
