### ISSUE TITLE
Career page - Fix EE indentation

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-labs-website#92]
Fix Electrical Engineering section indentation
I think the problem should be from the `electrical_engineer.md` file (thought i'd already fixed this in the previous PR)

**Comment by nathakits** [comment]
https://github.com/nathakits/pupil-labs-website/commit/423a1f9ff24b55474973d51dc57d20ad029af522
The PR is already merged but don't know why it's not working.

**Comment by nathakits** [comment]
Doesn't work in both desktop and mobile - only my localhost works...

**Comment by nathakits** [comment]
https://github.com/pupil-labs/pupil-labs-website/pull/93 - made a new PR to fix this issue

**Comment by willpatera** [comment]
It is a nested list. The indentation is intentional -- it was reverted from your previous PR. Please look through commit messages.
