### ISSUE TITLE
Blog - spacing between post date and post summary

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil-labs-website#97]
V spacing could be improved between date and text.
![screen shot 2016-09-10 at 16 30 33](https://cloud.githubusercontent.com/assets/1433767/18411244/fec9d692-7773-11e6-87cb-b871f45263e0.png)

**Comment by willpatera** [comment]
I assume you mean "date"

**Comment by mkassner** [comment]
yes !

**Comment by nathakits** [comment]
https://github.com/nathakits/pupil-labs-website/commit/34fc8d088e45aa4f5cfc3875171bd270cabac6c3 - add padding between post date and summary
